# Generated by Django 5.2.7 on 2025-10-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupil',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='age',
        ),
        migrations.AddField(
            model_name='pupil',
            name='last_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
