# Generated by Django 5.2.7 on 2025-10-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_rename_full_name_pupil_first_name_remove_pupil_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='group',
            field=models.CharField(blank=True, choices=[('1', 'Group 1'), ('2', 'Group 2')], max_length=1, null=True),
        ),
    ]
