# Generated by Django 5.2.7 on 2025-10-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_timeentry_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3),
        ),
    ]
